server:
  port: 8082
      
spring:    
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelServiceMicro
    username: postgres
    password: 123456  
     
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.mySQL8Dialect
      
  config:
    import: optional:configserver:http://localhost:8086       
#      
  application:
    name: HOTEL-SERVICE
#    
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true      


#okta configuration
okta:
  oauth2:
    issuer: https://dev-21763836.okta.com/oauth2/default      
    audience: api://default 
     