server:
  port: 8085


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:     
  application:
    name: "API-GATEWAY"
  
  cloud:
    gateway:
      routes:
        - id: CONFIG-DEFAULT-USERSERVICE
          uri: lb://CONFIG-DEFAULT-USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

   # okta configuration for API gateway       
          
okta:
  oauth2:
    issuer: https://dev-21763836.okta.com/oauth2/default      
    audience: api://default  
    client-id: 0oaeagc9hdy6Q4Uoj5d7
    client-secret: 0eDEbgN6iwwdDB6NU8YmEEWZ2NS2K79-yqTOWnPP8dIMXm5LX0zjFNleb1iDnVuP 
    scopes: openid, profile, email, offline_access    
    
    
     