server:
  port: 8081
spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/Demo_Microservice_ECommerse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.mySQL8Dialect
  application:
    name: AUTH-SERVICE

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/create

#        - id: CART-SERVICE
#          uri: lb://CART-SERVICE
#          predicates:
#            - Path=/ratings/**

  main:
    web-application-type: reactive



  config:
    import: optional:configserver:http://localhost:8086   
    
    
    
    
     